spring.application.name=BP
spring.datasource.url=jdbc:postgresql://localhost:5432/BPIridology
spring.datasource.username=BPUser
spring.datasource.password=BPUserPass
spring.datasource.hikari.schema=migrations
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.user=BPUser
spring.flyway.password=BPUserPass
spring.flyway.schemas=migrations
spring.flyway.create-schemas=true
spring.flyway.locations=classpath:db/migration