CREATE TABLE patient
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name     VARCHAR(255),
    last_name      VARCHAR(255),
    age            SMALLINT,
    birth_num      BIGINT,
    iridologist_id BIGINT,
    CONSTRAINT pk_patient PRIMARY KEY (id)
);

ALTER TABLE patient
    ADD CONSTRAINT FK_PATIENT_ON_IRIDOLOGIST FOREIGN KEY (iridologist_id) REFERENCES iridologist (id);