CREATE TABLE iris_map
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image_url      VARCHAR(255),
    iridologist_id BIGINT,
    CONSTRAINT pk_irismap PRIMARY KEY (id)
);

ALTER TABLE iris_map
    ADD CONSTRAINT FK_IRISMAP_ON_IRIDOLOGIST FOREIGN KEY (iridologist_id) REFERENCES iridologist (id);