CREATE TABLE iris_image
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image_url  VARCHAR(255),
    patient_id BIGINT,
    CONSTRAINT pk_irisimage PRIMARY KEY (id)
);

ALTER TABLE iris_image
    ADD CONSTRAINT FK_IRISIMAGE_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES patient (id);